/**
 * @author Liam
 */
package com.csu.fullerton.cpsc531.ui;

import com.csu.fullerton.cpsc531.obj.Contact;
import com.csu.fullerton.cpsc531.obj.Department;
import com.csu.fullerton.cpsc531.ui.utils.ImageFilter;
import com.datastax.driver.core.ResultSet;
import com.datastax.driver.core.Row;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.math.NumberUtils;

/**
 *
 * @author Peter
 */
public class InsertContact extends javax.swing.JFrame {

    private ListContact mainFrame;
    private File workingDirectory = new File(System.getProperty("user.dir"));
    private File defaultProfilePhoto = new File(getClass().getResource("/images/profile.png").getPath());
    private File file = defaultProfilePhoto;
    protected List<Department> departments = new ArrayList<>();
    protected List<Contact> management = new ArrayList<>();

    public InsertContact(ListContact parent) {
        initComponents();
        this.mainFrame = parent;
        ImageIcon imgicon = new ImageIcon(getClass().getResource("/images/icon.png").getPath());
        setIconImage(imgicon.getImage());
        setProfilePhoto(defaultProfilePhoto);
        DecimalFormat df = new java.text.DecimalFormat();
        df.setMaximumFractionDigits(2);
        df.setMinimumFractionDigits(2);
        df.setGroupingSize(3);
        txt_Salary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.NumberFormatter(df)));

        // Load once: all the departments at start-up;
        loadDepartments();

        // Load all the people that can be reported to
        loadManagement();

        txt_Salary.setValue(new Double(0.00));

        // go back to main frame (which is ListContact)
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                setVisible(false);
                mainFrame.setCenterOfTheScreen();
                mainFrame.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_company = new javax.swing.JFormattedTextField();
        txt_address1 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_address2 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_email = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_cellphone = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_telephone = new javax.swing.JFormattedTextField();
        _btn_reset = new javax.swing.JButton();
        _btn_add = new javax.swing.JButton();
        _btn_cancel = new javax.swing.JButton();
        _btn_photo = new javax.swing.JButton();
        btn_removePhoto = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        combo_department = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        combo_report_to = new javax.swing.JComboBox<>();
        combo_role = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_Salary = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Contact");
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Company:");

        txt_firstname.setForeground(new java.awt.Color(0, 153, 51));
        txt_firstname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_firstname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Last Name:");

        txt_lastname.setForeground(new java.awt.Color(0, 153, 51));
        txt_lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_lastname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("First Name:");

        txt_company.setForeground(new java.awt.Color(0, 153, 51));
        txt_company.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_company.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        txt_address1.setForeground(new java.awt.Color(0, 153, 51));
        txt_address1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_address1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Address 1:");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Address 2:");

        txt_address2.setForeground(new java.awt.Color(0, 153, 51));
        txt_address2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_address2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email:");

        txt_email.setForeground(new java.awt.Color(0, 153, 51));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setToolTipText("example: johndoe@company.com");
        txt_email.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Cell Phone:");

        txt_cellphone.setForeground(new java.awt.Color(0, 153, 51));
        txt_cellphone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cellphone.setToolTipText("XXX-XXX-XXXX");
        txt_cellphone.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Telephone:");

        txt_telephone.setForeground(new java.awt.Color(0, 153, 51));
        txt_telephone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_telephone.setToolTipText("XXX-XXX-XXXX");
        txt_telephone.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        _btn_reset.setBackground(java.awt.SystemColor.activeCaption);
        _btn_reset.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        _btn_reset.setForeground(new java.awt.Color(0, 102, 51));
        _btn_reset.setMnemonic('r');
        _btn_reset.setText("RESET");
        _btn_reset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        _btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_resetActionPerformed(evt);
            }
        });

        _btn_add.setBackground(java.awt.SystemColor.activeCaption);
        _btn_add.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        _btn_add.setForeground(new java.awt.Color(0, 102, 51));
        _btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        _btn_add.setMnemonic('A');
        _btn_add.setText("ADD");
        _btn_add.setMargin(new java.awt.Insets(0, 0, 0, 0));
        _btn_add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_rollover.png"))); // NOI18N
        _btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_addActionPerformed(evt);
            }
        });

        _btn_cancel.setBackground(java.awt.SystemColor.activeCaption);
        _btn_cancel.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        _btn_cancel.setForeground(new java.awt.Color(0, 102, 51));
        _btn_cancel.setMnemonic('C');
        _btn_cancel.setText("CANCEL");
        _btn_cancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        _btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_cancelActionPerformed(evt);
            }
        });

        _btn_photo.setBackground(java.awt.SystemColor.activeCaption);
        _btn_photo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        _btn_photo.setForeground(new java.awt.Color(0, 102, 51));
        _btn_photo.setMnemonic('r');
        _btn_photo.setText("+ Photo");
        _btn_photo.setActionCommand("");
        _btn_photo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        _btn_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_photoActionPerformed(evt);
            }
        });

        btn_removePhoto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_removePhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        btn_removePhoto.setMnemonic('A');
        btn_removePhoto.setToolTipText("Remove a selected photo");
        btn_removePhoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_removePhoto.setIconTextGap(0);
        btn_removePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_removePhotoMouseEntered(evt);
            }
        });
        btn_removePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removePhotoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Department:");

        combo_department.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        combo_department.setForeground(new java.awt.Color(0, 153, 51));
        combo_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MKT" }));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Reports to:");

        combo_report_to.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        combo_report_to.setForeground(new java.awt.Color(0, 153, 51));
        combo_report_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        combo_role.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        combo_role.setForeground(new java.awt.Color(0, 153, 51));
        combo_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Manager", "Supervisor", "CEO", "CFO", "Other" }));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Role:");

        txt_Salary.setForeground(new java.awt.Color(0, 153, 51));
        txt_Salary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        txt_Salary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Salary.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Salary:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_btn_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(_btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_firstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(7, 7, 7))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(combo_report_to, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(combo_department, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(_btn_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_removePhoto))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_department, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_report_to, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combo_department, combo_report_to, combo_role, txt_Salary, txt_address1, txt_address2, txt_cellphone, txt_company, txt_email, txt_firstname, txt_lastname, txt_telephone});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Load all the departments
    protected void loadDepartments() {
        departments = mainFrame.cassandra.selectAllDepartments();
        combo_department.removeAllItems();
        for (Department department : departments) {
            combo_department.addItem(department.toString());
        }
    }

    public void setCenterOfTheScreen() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2 - 10);
    }

    // Load all the people that can be reported to
    protected void loadManagement() {
        combo_report_to.removeAllItems();
        ResultSet resultSet = mainFrame.cassandra.selectAllContacts();
        management.clear();
        for (Row row : resultSet) {
            Contact c = new Contact();
            String role = row.getString("role");
            c.setContactId(row.getUUID("id"));
            c.setFirstname(row.getString("firstname"));
            c.setLastname(row.getString("lastname"));
            c.setCompany(row.getString("company"));
            c.setAddress1(row.getString("address1"));
            c.setAddress2(row.getString("address2"));
            c.setEmail(row.getString("email"));
            c.setTelephone(row.getString("telephone"));
            c.setCellphone(row.getString("cellphone"));
            c.setRole(role);
            c.setSalary(row.getDouble("salary"));
            c.setReport_to(row.getUUID("report_to"));
            c.setDepartment_code(row.getString("department_code"));
            if (!c.getRole().equals("Employee") && !c.getRole().equals("Other")) {
                management.add(c);
            }
        }

        // Sort by Lastname
        java.util.Collections.sort(management, new Comparator<Contact>() {
            @Override
            public int compare(Contact t, Contact t1) {
                Contact p1 = (Contact) t;
                Contact p2 = (Contact) t1;
                // if last names are the same compare first names
                if (p1.getLastname().equals(p2.getLastname())) {
                    return p1.getFirstname().compareTo(p2.getFirstname());
                }
                return p1.getLastname().compareTo(p2.getLastname());
            }
        });

        // items for report-to combobox
        combo_report_to.addItem("None");
        for (Contact c : management) {
            System.out.println("ROLE: " + c.getRole());
            combo_report_to.addItem(StringUtils.rightPad(c.getDepartment_code(), 6) + c.toString() + " - " + c.getRole());
        }
    }

    // Reset form
    private void _btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_resetActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you want to reset the form?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            reset();
        }
    }//GEN-LAST:event__btn_resetActionPerformed

    // Insert contact
    private void _btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_addActionPerformed
        String validateMsg = validateInput();
        if (validateMsg.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    validateMsg,
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE,
                    mainFrame.imgIcon_info);
        } else {
            Contact contact = getContact();
            mainFrame.cassandra.insertContact(contact);
            reset();

            int dialogResult = JOptionPane.showConfirmDialog(null, "The contact is inserted.\nWould You Like to insert other contact?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                txt_firstname.requestFocus();
            } else {
                mainFrame.loadContacts(mainFrame.cassandra.selectAllContacts());
                setVisible(false);
                mainFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event__btn_addActionPerformed

    // cancel button action
    private void _btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_cancelActionPerformed
        setVisible(false);
        reset();
        mainFrame.setVisible(true);
    }//GEN-LAST:event__btn_cancelActionPerformed

    // select profile photo button's action
    private void _btn_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_photoActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(workingDirectory);
        fc.setFileFilter(new ImageFilter());
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            //System.out.println("->" + file.getParent());
            //System.out.println("->" + workingDirectory.getPath());

        }
        setProfilePhoto(file);

    }//GEN-LAST:event__btn_photoActionPerformed

    // read and set photo from file
    private void setProfilePhoto(File file) {
        ImageIcon icon;
        try {
            icon = new ImageIcon(ImageIO.read(file));
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(165, 165, java.awt.Image.SCALE_SMOOTH);
            _btn_photo.setText("");
            _btn_photo.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
            Logger.getLogger(InsertContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btn_removePhotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removePhotoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removePhotoMouseEntered

    // remove photo
    private void btn_removePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removePhotoActionPerformed
        file = null;
        setProfilePhoto(defaultProfilePhoto);
    }//GEN-LAST:event_btn_removePhotoActionPerformed

    // reset the form
    private void reset() {
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_company.setText("");
        txt_address1.setText("");
        txt_address2.setText("");
        txt_email.setText("");
        txt_telephone.setText("");
        txt_cellphone.setText("");
        combo_role.setSelectedIndex(0);
        combo_department.setSelectedIndex(0);
        combo_report_to.setSelectedIndex(0);
        txt_Salary.setValue(new Double(0.00));
        file = null;
        setProfilePhoto(defaultProfilePhoto);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InsertContact(new ListContact()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_add;
    private javax.swing.JButton _btn_cancel;
    private javax.swing.JButton _btn_photo;
    private javax.swing.JButton _btn_reset;
    private javax.swing.JButton btn_removePhoto;
    private javax.swing.JComboBox<String> combo_department;
    private javax.swing.JComboBox<String> combo_report_to;
    private javax.swing.JComboBox<String> combo_role;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txt_Salary;
    private javax.swing.JFormattedTextField txt_address1;
    private javax.swing.JFormattedTextField txt_address2;
    private javax.swing.JFormattedTextField txt_cellphone;
    private javax.swing.JFormattedTextField txt_company;
    private javax.swing.JFormattedTextField txt_email;
    private javax.swing.JFormattedTextField txt_firstname;
    private javax.swing.JFormattedTextField txt_lastname;
    private javax.swing.JFormattedTextField txt_telephone;
    // End of variables declaration//GEN-END:variables

    private Contact getContact() {
        String first = txt_firstname.getText();
        String last = txt_lastname.getText();
        String company = txt_company.getText();
        String address1 = txt_address1.getText();
        String address2 = txt_address2.getText();
        String email = txt_email.getText();
        String telephone = txt_telephone.getText();
        String cellphone = txt_cellphone.getText();
        String role = combo_role.getSelectedItem().toString();

        String department = combo_department.getSelectedItem().toString();

        Contact contact = new Contact(first, last, company, address1, address2, email, telephone, cellphone, role);
        contact.setSalary(NumberUtils.toDouble(txt_Salary.getValue().toString()));

        int reportTo = combo_report_to.getSelectedIndex();
        if (reportTo > 0) {
            contact.setReport_to(management.get(reportTo - 1).getContactId());
        }

        // set photo profile to the contact
        try {
            if (file == null) {
                file = defaultProfilePhoto;
            }
            InputStream fis = new FileInputStream(file);
            byte[] bytes = new byte[fis.available() + 1];

            fis.read(bytes);
            ByteBuffer buffer = ByteBuffer.wrap(bytes);
            contact.setPhoto(buffer);
            fis.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InsertContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InsertContact.class.getName()).log(Level.SEVERE, null, ex);
        }

        contact.setDepartment_code(department);
        return contact;
    }

    private String validateInput() {
        String message = "";
        if (txt_firstname.getText().trim().length() <= 0) {
            message += "First Name is required. \n";
        }
        if (txt_lastname.getText().trim().length() <= 0) {
            message += "Last Name is required. \n";
        }
        String email = txt_email.getText().trim();
        if (email.length() > 0 && !Validator.isEmail(email)) {
            message += "Email is invalid. \n";
        }

        String phone = txt_telephone.getText().trim();
        if (phone.length() > 0 && !Validator.isPhone(phone)) {
            message += "Telephone number is invalid. \n";
        }

        phone = txt_cellphone.getText().trim();
        if (phone.length() > 0 && !Validator.isPhone(phone)) {
            message += "Cell phone number is invalid. \n";
        }

        return message;
    }
}
